### ISSUE TITLE
实时猫希望和您建立联系

### ISSUE THREAD

**Issue by betaver** [szoliver/RTC.Net#1]
soliver 您好，

我是实时猫的负责人韩锐 (han@learning-tech.com)，我们团队的工程师一直在关注您的 szoliver/RTC.Net，并想与您建立联系，来：

- 更好地跟踪和完善这个项目，帮助更多人更容易地使用WebRTC技术
- 为您提供我们产品的发展信息和礼品
- 互相认识了解
- 在实时猫未来正式版本的官网上推广这个项目

请拨冗发一封邮件到 han@learning-tech.com ，包含您的联系方式。 咱再具体聊，交流技术，交个朋友。

~韩锐

**Comment by betaver** [comment]
@RTCat

**Comment by szoliver** [comment]
已加实时猫官方交流群 530719965，Orman就是我。 @betaver
